# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76f6cc465f5d2598b7c02028c41380689ca969c4b86a4e9486caca7e4ba8692e23be29a3d7b333e65e64011a45e38557cb78baffd1b04d2049c9fc535612b34e

test:
  secret_key_base: f96ea1761f62e3502ae78d35c20f7e8b8b82d06424072ebd01e9f8908ae67b71f33ca0c0fe5b27e2a24febf0eb758a23884c5665d276fc26192e9fc685569004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
